# Generated by Django 3.2 on 2023-02-16 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='评论')),
            ],
        ),
        migrations.CreateModel(
            name='MH_PersonalDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover', models.ImageField(default='cover.jpg', upload_to='cover', verbose_name='封面')),
                ('name', models.CharField(max_length=32, verbose_name='姓名')),
                ('gender', models.CharField(choices=[('1', '男'), ('2', '女')], max_length=2, verbose_name='性别')),
                ('age', models.CharField(max_length=32, verbose_name='年龄')),
                ('region', models.CharField(max_length=32, verbose_name='地区')),
                ('school', models.CharField(max_length=32, verbose_name='学校')),
                ('contact', models.CharField(max_length=32, verbose_name='联系方式')),
                ('introduction', models.TextField(verbose_name='个人简介')),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=32, verbose_name='学校')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portrait', models.ImageField(default='portrait.jpg', upload_to='portrait', verbose_name='头像')),
                ('user_name', models.CharField(max_length=32, verbose_name='用户名')),
                ('account', models.CharField(max_length=32, unique=True, verbose_name='账号')),
                ('password', models.CharField(max_length=32, verbose_name='密码')),
                ('region', models.CharField(max_length=32, verbose_name='地区')),
            ],
        ),
        migrations.CreateModel(
            name='Mailbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mailbox', models.CharField(max_length=32, verbose_name='邮箱')),
                ('userinfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GHMHAPP.userinfo', verbose_name='用户')),
            ],
        ),
        migrations.CreateModel(
            name='Comment_comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='评论的评论')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GHMHAPP.comment', verbose_name='盲盒评论')),
                ('userinfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GHMHAPP.userinfo', verbose_name='昵称')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GHMHAPP.mh_personaldetail', verbose_name='盲盒'),
        ),
        migrations.AddField(
            model_name='comment',
            name='userinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GHMHAPP.userinfo', verbose_name='昵称'),
        ),
    ]
